"""empty message

Revision ID: 7a969cfa89c7
Revises:
Create Date: 2017-07-15 11:55:57.701590

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from console_cowboys.models import Job


# revision identifiers, used by Alembic.
revision = '7a969cfa89c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=90), nullable=False),
    sa.Column('location', sa.String(length=90), nullable=False),
    sa.Column('contract_type', sqlalchemy_utils.types.choice.ChoiceType(Job.CONTRACT_TYPES), nullable=False),
    sa.Column('company_name', sa.String(length=90), nullable=False),
    sa.Column('listing_url', sa.String(length=90), nullable=False),
    sa.Column('is_remote', sa.Boolean(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('charge_id', sa.String(length=70), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job')
    # ### end Alembic commands ###
